server_port: 8080
backup_directory: "E:/BackupData" # Приклад шляху для Windows
database_path: "./data/backup.db"
secret_salt: "mySuperLongAndRandomSaltForHashingPasswords" # Згенеруйте ДОВГИЙ, УНІКАЛЬНИЙ, випадковий рядок для вашого проекту!

read_timeout: "5s"    # 5 секунд для читання запиту
write_timeout: "10s"   # 10 секунд для запису відповіді
idle_timeout: "60s"    # 60 секунд для утримання неактивного з'єднання

shutdown_timeout: "15s" # Максимальний час для коректного завершення роботи сервера